//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViolationSystem.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using ViolationSystem.Data.Entities;

	public partial class AppDbContext : DbContext
    {
        public AppDbContext()
            : base("name=SqlConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<Violation> Violations { get; set; }
    }
}
