//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViolationSystem.Data.Entities
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class Violation
	{
		public int Id { get; set; }
		[DisplayName("تاريخ المخالفة")]
		[Required(ErrorMessage = "تاريخ المخالفة مطلوب")]
        public System.DateTime ViolationDate { get; set; }
		public virtual Truck Truck { get; set; }
		[DisplayName("رقم الشاحنة")]
		[NotMapped]
		public string TruckCode { get => Truck?.Code; set => Truck.Code = value; }
        [DisplayName("الوزن")]
		public string Weight { get; set; }
		[DisplayName("الحمولة")]
		public string Payload { get; set; }
		[DisplayName("رقم البلاغ")]
		public string ReportNumber { get; set; }
		[DisplayName("تاريخ السداد")]
		public Nullable<System.DateTime> PaymentDate { get; set; }
		
		[DisplayName("تاريخ الحجز الإداري")]
		public Nullable<System.DateTime> BlockDate { get; set; }

		[DisplayName("الوحدة المسؤولة")]
		public string ResponsibleUnit { get; set; }
        
		public int TruckId { get; set; }
    
    }
}
