//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViolationsCollecting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using ViolationsCollecting.Model.Entities;

	public partial class ViolationsDB : DbContext
    {
        public ViolationsDB()
            : base("name=ViolationsDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<Violation> Violations { get; set; }
    }
}
